# BLE表示名
CONFIG_ZMK_KEYBOARD_NAME="Dark Repulser"

# NFC ピンを GPIO として使用（BLE干渉防止）
CONFIG_NFCT_PINS_AS_GPIOS=y

# 接続後に自動でパラメータ再交渉
CONFIG_BT_GAP_AUTO_UPDATE_CONN_PARAMS=y
CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT=1000

CONFIG_BT_CTLR_PHY_2M=y
CONFIG_BT_AUTO_PHY_UPDATE=y

# Rotary encoder（左手スレーブ専用）
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_OWN_THREAD=y   # ← 記事の核心
CONFIG_EC11_THREAD_PRIORITY=14
CONFIG_EC11_THREAD_STACK_SIZE=4096
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y
CONFIG_ZMK_BATTERY_REPORTING=y

# BLE TX出力を上げる（左右間の接続安定化）
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# スリープ設定（R側と合わせる）
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000

# Boot Retention（&bootloader 新方式）
CONFIG_RETAINED_MEM=y
CONFIG_RETENTION=y
CONFIG_RETENTION_BOOT_MODE=y
CONFIG_RETENTION_BOOT_MODE=y
